export type DuctingImage = {
  src: string;
  type: "ducting";
  name: string;
};

export const ductingImages = [
  { src: "/ducting/ducting_2.JPG", type: "ducting", name: "ducting_2" },
  { src: "/ducting/ducting_3.JPG", type: "ducting", name: "ducting_3" },
  { src: "/ducting/ducting_4.JPG", type: "ducting", name: "ducting_4" },
  { src: "/ducting/ducting_5.JPG", type: "ducting", name: "ducting_5" },
  { src: "/ducting/ducting_6.JPG", type: "ducting", name: "ducting_6" },
  { src: "/ducting/ducting_7.JPG", type: "ducting", name: "ducting_7" },
  { src: "/ducting/ducting_8.JPG", type: "ducting", name: "ducting_8" },
  { src: "/ducting/ducting_9.JPG", type: "ducting", name: "ducting_9" },
  { src: "/ducting/ducting_10.JPG", type: "ducting", name: "ducting_10" },
  { src: "/ducting/ducting_11.JPG", type: "ducting", name: "ducting_11" },
  { src: "/ducting/ducting_12.JPG", type: "ducting", name: "ducting_12" },
  { src: "/ducting/ducting_13.JPG", type: "ducting", name: "ducting_13" },
  { src: "/ducting/ducting_14.JPG", type: "ducting", name: "ducting_14" },

  {
    src: "/insulation/insulation_1.JPG",
    type: "insulation",
    name: "insulation_1",
  },
  {
    src: "/insulation/insulation_2.JPG",
    type: "insulation",
    name: "insulation_2",
  },
  {
    src: "/insulation/insulation_3.JPG",
    type: "insulation",
    name: "insulation_3",
  },
  {
    src: "/insulation/insulation_4.JPG",
    type: "insulation",
    name: "insulation_4",
  },
  {
    src: "/insulation/insulation_5.JPG",
    type: "insulation",
    name: "insulation_5",
  },
  {
    src: "/insulation/insulation_6.JPG",
    type: "insulation",
    name: "insulation_6",
  },
  {
    src: "/insulation/insulation_7.JPG",
    type: "insulation",
    name: "insulation_7",
  },
  {
    src: "/insulation/insulation_8.JPG",
    type: "insulation",
    name: "insulation_8",
  },
  {
    src: "/insulation/insulation_9.JPG",
    type: "insulation",
    name: "insulation_9",
  },
  {
    src: "/insulation/insulation_10.JPG",
    type: "insulation",
    name: "insulation_10",
  },
  {
    src: "/insulation/insulation_11.JPG",
    type: "insulation",
    name: "insulation_11",
  },
  {
    src: "/insulation/insulation_12.JPG",
    type: "insulation",
    name: "insulation_12",
  },
  {
    src: "/insulation/insulation_13.JPG",
    type: "insulation",
    name: "insulation_13",
  },
  { src: "/safety/IMG_5748.JPG", type: "safety", name: "safety_1" },
  { src: "/safety/IMG_5749.JPG", type: "safety", name: "safety_2" },
  { src: "/safety/IMG_5750.JPG", type: "safety", name: "safety_3" },
  { src: "/safety/IMG_5751.JPG", type: "safety", name: "safety_4" },
  { src: "/safety/IMG_5752.JPG", type: "safety", name: "safety_5" },
  { src: "/safety/IMG_5753.JPG", type: "safety", name: "safety_6" },
  { src: "/safety/IMG_5754.JPG", type: "safety", name: "safety_7" },
  { src: "/safety/IMG_5755.JPG", type: "safety", name: "safety_8" },
  { src: "/safety/IMG_5756.JPG", type: "safety", name: "safety_9" },
  { src: "/safety/IMG_5757.JPG", type: "safety", name: "safety_10" },
  { src: "/safety/IMG_5758.JPG", type: "safety", name: "safety_11" },
  { src: "/safety/IMG_5759.JPG", type: "safety", name: "safety_12" },
  { src: "/safety/IMG_5760.JPG", type: "safety", name: "safety_13" },
  { src: "/safety/IMG_5761.JPG", type: "safety", name: "safety_14" },
  { src: "/safety/IMG_5762.JPG", type: "safety", name: "safety_15" },
  { src: "/safety/IMG_5763.JPG", type: "safety", name: "safety_16" },
  { src: "/safety/IMG_5764.JPG", type: "safety", name: "safety_17" },
  { src: "/safety/IMG_5765.JPG", type: "safety", name: "safety_18" },
  { src: "/safety/IMG_5766.JPG", type: "safety", name: "safety_19" },
  { src: "/safety/IMG_5767.JPG", type: "safety", name: "safety_20" },
  { src: "/safety/IMG_5768.JPG", type: "safety", name: "safety_21" },
  { src: "/safety/IMG_5769.JPG", type: "safety", name: "safety_22" },
  { src: "/safety/IMG_5770.JPG", type: "safety", name: "safety_23" },
  { src: "/safety/IMG_5771.JPG", type: "safety", name: "safety_24" },
  { src: "/safety/IMG_5772.JPG", type: "safety", name: "safety_25" },
  { src: "/safety/IMG_5773.JPG", type: "safety", name: "safety_26" },
  { src: "/safety/IMG_5774.JPG", type: "safety", name: "safety_27" },
  { src: "/safety/IMG_5775.JPG", type: "safety", name: "safety_28" },
  { src: "/safety/IMG_5776.JPG", type: "safety", name: "safety_29" },
  { src: "/safety/IMG_5777.JPG", type: "safety", name: "safety_30" },
  { src: "/safety/IMG_5778.JPG", type: "safety", name: "safety_31" },
  { src: "/safety/IMG_5779.JPG", type: "safety", name: "safety_32" },
  { src: "/safety/IMG_5780.JPG", type: "safety", name: "safety_33" },
  { src: "/safety/IMG_5781.JPG", type: "safety", name: "safety_34" },
  { src: "/safety/IMG_5787.JPG", type: "safety", name: "safety_35" },
  { src: "/safety/IMG_5788.JPG", type: "safety", name: "safety_36" },
  { src: "/safety/IMG_5789.JPG", type: "safety", name: "safety_37" },
  { src: "/safety/IMG_5790.JPG", type: "safety", name: "safety_38" },
  { src: "/safety/IMG_5791.JPG", type: "safety", name: "safety_39" },
  { src: "/safety/IMG_5792.JPG", type: "safety", name: "safety_40" },
  { src: "/safety/IMG_5793.JPG", type: "safety", name: "safety_41" },
  { src: "/safety/IMG_5794.JPG", type: "safety", name: "safety_42" },
  { src: "/safety/IMG_5795.JPG", type: "safety", name: "safety_43" },
  { src: "/safety/IMG_5796.JPG", type: "safety", name: "safety_44" },
  { src: "/safety/IMG_5797.JPG", type: "safety", name: "safety_45" },
  { src: "/safety/IMG_5798.JPG", type: "safety", name: "safety_46" },
  { src: "/safety/IMG_5799.JPG", type: "safety", name: "safety_47" },
  { src: "/safety/IMG_5800.JPG", type: "safety", name: "safety_48" },
  { src: "/safety/IMG_5801.JPG", type: "safety", name: "safety_49" },
  { src: "/safety/IMG_5802.JPG", type: "safety", name: "safety_50" },
  { src: "/safety/IMG_5811.JPG", type: "safety", name: "safety_51" },
  { src: "/safety/IMG_5812.JPG", type: "safety", name: "safety_52" },
  { src: "/safety/IMG_5813.JPG", type: "safety", name: "safety_53" },
  { src: "/safety/IMG_5814.JPG", type: "safety", name: "safety_54" },
  { src: "/safety/IMG_5815.JPG", type: "safety", name: "safety_55" },
  { src: "/safety/IMG_5816.JPG", type: "safety", name: "safety_56" },
  { src: "/safety/IMG_5817.JPG", type: "safety", name: "safety_57" },
  { src: "/safety/IMG_5818.JPG", type: "safety", name: "safety_58" },
  { src: "/safety/IMG_5819.JPG", type: "safety", name: "safety_59" },
  { src: "/safety/IMG_5820.JPG", type: "safety", name: "safety_60" },
  { src: "/safety/IMG_5821.JPG", type: "safety", name: "safety_61" },
  { src: "/safety/IMG_5822.JPG", type: "safety", name: "safety_62" },
  { src: "/safety/IMG_5823.JPG", type: "safety", name: "safety_63" },
  { src: "/safety/IMG_5824.JPG", type: "safety", name: "safety_64" },
  { src: "/safety/IMG_5825.JPG", type: "safety", name: "safety_65" },
  { src: "/safety/IMG_5826.JPG", type: "safety", name: "safety_66" },
  { src: "/safety/IMG_5827.JPG", type: "safety", name: "safety_67" },
  { src: "/safety/safety_1.JPG", type: "safety", name: "safety_68" },
  { src: "/safety/safety_2.JPG", type: "safety", name: "safety_69" },
];
